[telegram]
api_key = "your api key"
worker_count = 20
admin = "your user name"
bot_name = "stickerfinder"

[database]
sql_uri = "postgres://localhost/stickerfinder"
connection_count = 20
overflow_count = 10

[logging]
sentry_enabled = false
sentry_token = "your sentry token"
log_level = 20
debug = false

[webhook]
enabled = false
domain = "https://localhost"
token = "stickerfinder"
cert_path = "/path/to/cert.pem"
port = 7000

[job]
user_check_count = 200
report_count = 5

[mode]
leecher = false
