"""Tasks

Revision ID: 199b4c5329ac
Revises: 97be35ea927d
Create Date: 2018-10-03 23:04:46.443309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '199b4c5329ac'
down_revision = '97be35ea927d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'task',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('type', sa.String(), nullable=True),
        sa.Column('reviewed', sa.Boolean(), server_default='FALSE', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('sticker_set_name', sa.String(), nullable=True),
        sa.CheckConstraint('(user_id IS NOT NULL AND sticker_set_name IS NULL) OR                          (user_id IS NULL AND sticker_set_name IS NOT NULL)'),
        sa.ForeignKeyConstraint(['sticker_set_name'], ['sticker_set.name']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_task_sticker_set_name'), 'task', ['sticker_set_name'], unique=False)
    op.create_index(op.f('ix_task_user_id'), 'task', ['user_id'], unique=False)
    op.add_column('chat', sa.Column('current_task_id', postgresql.UUID(), nullable=True))
    op.create_index(op.f('ix_chat_current_task_id'), 'chat', ['current_task_id'], unique=False)
    op.create_foreign_key(None, 'chat', 'task', ['current_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_index(op.f('ix_chat_current_task_id'), table_name='chat')
    op.drop_column('chat', 'current_task_id')
    op.drop_index(op.f('ix_task_user_id'), table_name='task')
    op.drop_index(op.f('ix_task_sticker_set_name'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
