"""Add furry tag

Revision ID: 85ad52b28135
Revises: 8dc9f8aff0b1
Create Date: 2018-10-22 20:36:04.416947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ad52b28135'
down_revision = '8dc9f8aff0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sticker_set', sa.Column('furry', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sticker_set', 'furry')
    # ### end Alembic commands ###
