"""Cascade on task delete

Revision ID: ef5c7ce8e2b7
Revises: ad8be3fcd898
Create Date: 2018-10-14 22:06:34.215120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5c7ce8e2b7'
down_revision = 'ad8be3fcd898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_current_task_id_fkey', 'chat', type_='foreignkey')
    op.create_foreign_key(None, 'chat', 'task', ['current_task_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.create_foreign_key('chat_current_task_id_fkey', 'chat', 'task', ['current_task_id'], ['id'])
    # ### end Alembic commands ###
