"""inline search

Revision ID: 8dc9f8aff0b1
Revises: 963070a023d2
Create Date: 2018-10-21 23:51:41.118146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8dc9f8aff0b1'
down_revision = '963070a023d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inline_search', sa.Column('search_id', sa.BigInteger(), nullable=False, primary_key=True, autoincrement=True))
    op.drop_column('inline_search', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inline_search', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False, primary_key=True))
    op.drop_column('inline_search', 'search_id')
    # ### end Alembic commands ###
