"""Chat flags

Revision ID: fd4744f74703
Revises: a3c459e8860a
Create Date: 2018-09-30 14:35:57.515919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4744f74703'
down_revision = 'a3c459e8860a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('is_ban', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('chat', sa.Column('is_maintenance', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('chat', sa.Column('is_newsfeed', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('sticker_set', sa.Column('banned', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('sticker_set', sa.Column('newsfeed_sent', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sticker_set', 'newsfeed_sent')
    op.drop_column('sticker_set', 'banned')
    op.drop_column('chat', 'is_newsfeed')
    op.drop_column('chat', 'is_maintenance')
    op.drop_column('chat', 'is_ban')
    # ### end Alembic commands ###
