"""Add sticker set language

Revision ID: fd5458abc68a
Revises: 9c0ccea0f519
Create Date: 2018-11-14 12:16:22.343127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5458abc68a'
down_revision = '9c0ccea0f519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sticker_set', sa.Column('language', sa.String(), server_default='english', nullable=True))
    op.create_index(op.f('ix_sticker_set_language'), 'sticker_set', ['language'], unique=False)
    op.create_foreign_key(None, 'sticker_set', 'language', ['language'], ['name'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sticker_set', type_='foreignkey')
    op.drop_index(op.f('ix_sticker_set_language'), table_name='sticker_set')
    op.drop_column('sticker_set', 'language')
    # ### end Alembic commands ###
