"""Add tag emoji flag and completely tagged flag

Revision ID: a3c459e8860a
Revises: 60be4019a8eb
Create Date: 2018-09-27 11:46:37.519936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c459e8860a'
down_revision = '60be4019a8eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sticker_set', sa.Column('completely_tagged', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('tag', sa.Column('emoji', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'emoji')
    op.drop_column('sticker_set', 'completely_tagged')
    # ### end Alembic commands ###
