"""Remove useless indices and columns

Revision ID: 60be4019a8eb
Revises: 2f3f005f663d
Create Date: 2018-09-26 23:47:31.377181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60be4019a8eb'
down_revision = '2f3f005f663d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sticker_name', table_name='sticker')
    op.drop_index('ix_sticker_text', table_name='sticker')
    op.drop_column('sticker', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sticker', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_sticker_text', 'sticker', ['text'], unique=False)
    op.create_index('ix_sticker_name', 'sticker', ['name'], unique=False)
    # ### end Alembic commands ###
