"""Language delete cascades.

Revision ID: dd1bcd34b36d
Revises: 69f7d688a411
Create Date: 2018-11-06 19:08:58.056022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1bcd34b36d'
down_revision = '69f7d688a411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('change_language_fkey', 'change', type_='foreignkey')
    op.create_foreign_key(None, 'change', 'language', ['language'], ['name'], onupdate='cascade', ondelete='cascade')
    op.drop_constraint('tag_language_fkey', 'tag', type_='foreignkey')
    op.create_foreign_key(None, 'tag', 'language', ['language'], ['name'], onupdate='cascade', ondelete='cascade')
    op.drop_constraint('user_language_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'language', ['language'], ['name'], onupdate='cascade', ondelete='set default')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_language_fkey', 'user', 'language', ['language'], ['name'])
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.create_foreign_key('tag_language_fkey', 'tag', 'language', ['language'], ['name'])
    op.drop_constraint(None, 'change', type_='foreignkey')
    op.create_foreign_key('change_language_fkey', 'change', 'language', ['language'], ['name'])
    # ### end Alembic commands ###
