"""BigInt and vote ban.

Revision ID: 7d6fd72f32db
Revises: fd4744f74703
Create Date: 2018-09-30 16:29:27.207525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6fd72f32db'
down_revision = 'fd4744f74703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'vote_ban',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reason', sa.String(), nullable=True),
        sa.Column('old_tags', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('sticker_set_name', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['sticker_set_name'], ['sticker_set.name']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_vote_ban_sticker_set_name'), 'vote_ban', ['sticker_set_name'], unique=False)
    op.create_index(op.f('ix_vote_ban_user_id'), 'vote_ban', ['user_id'], unique=False)
    op.alter_column(
        'change', 'user_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.drop_index('ix_change_new_tags', table_name='change')
    op.drop_index('ix_change_new_text', table_name='change')
    op.drop_index('ix_change_old_tags', table_name='change')
    op.drop_index('ix_change_old_text', table_name='change')
    op.alter_column(
        'chat', 'id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        autoincrement=True,
        existing_server_default=sa.text("nextval('chat_id_seq'::regclass)"),
    )
    op.alter_column(
        'chat_sticker_set', 'chat_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        'user', 'id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user', 'id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        autoincrement=True,
    )
    op.alter_column(
        'chat_sticker_set', 'chat_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        'chat', 'id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        autoincrement=True,
        existing_server_default=sa.text("nextval('chat_id_seq'::regclass)"),
    )
    op.create_index('ix_change_old_text', 'change', ['old_text'], unique=False)
    op.create_index('ix_change_old_tags', 'change', ['old_tags'], unique=False)
    op.create_index('ix_change_new_text', 'change', ['new_text'], unique=False)
    op.create_index('ix_change_new_tags', 'change', ['new_tags'], unique=False)
    op.alter_column(
        'change', 'user_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.drop_index(op.f('ix_vote_ban_user_id'), table_name='vote_ban')
    op.drop_index(op.f('ix_vote_ban_sticker_set_name'), table_name='vote_ban')
    op.drop_table('vote_ban')
    # ### end Alembic commands ###
