"""Fuck languages part 2

Revision ID: 6c854954ca33
Revises:
Create Date: 2018-11-30 01:43:53.138916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c854954ca33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change', 'language')
    op.drop_column('sticker_set', 'language')
    op.drop_column('tag', 'language')
    op.drop_column('user', 'language')
    op.alter_column('task', 'default_language',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.VARCHAR(), server_default=sa.text("'english'::character varying"), autoincrement=False, nullable=True))
    op.alter_column('task', 'default_language',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.add_column('tag', sa.Column('language', sa.VARCHAR(), server_default=sa.text("'english'::character varying"), autoincrement=False, nullable=True))
    op.add_column('sticker_set', sa.Column('language', sa.VARCHAR(), server_default=sa.text("'english'::character varying"), autoincrement=False, nullable=True))
    op.add_column('change', sa.Column('language', sa.VARCHAR(), server_default=sa.text("'english'::character varying"), autoincrement=False, nullable=True))
