"""Missing columns.

Revision ID: 69f7d688a411
Revises: 157ccc4d9d0b
Create Date: 2018-11-06 17:17:37.653967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f7d688a411'
down_revision = '157ccc4d9d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change', sa.Column('language', sa.String(), server_default='english', nullable=True))
    op.create_index(op.f('ix_change_language'), 'change', ['language'], unique=False)
    op.create_foreign_key(None, 'change', 'language', ['language'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'change', type_='foreignkey')
    op.drop_index(op.f('ix_change_language'), table_name='change')
    op.drop_column('change', 'language')
    # ### end Alembic commands ###
