"""query offset

Revision ID: 8fc208f074b8
Revises: d4ec0cd1dff4
Create Date: 2018-10-24 15:30:26.969069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc208f074b8'
down_revision = 'd4ec0cd1dff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inline_search', sa.Column('offset', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inline_search', 'offset')
    # ### end Alembic commands ###
