"""Gin index.

Revision ID: d4ec0cd1dff4
Revises: 85ad52b28135
Create Date: 2018-10-18 12:31:11.437711

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd4ec0cd1dff4'
down_revision = '85ad52b28135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sticker_text_idx', 'sticker', ['text'], unique=False, postgresql_using='gin', postgresql_ops={'text': 'gin_trgm_ops'})
    op.create_index('sticker_set_name_gin_idx', 'sticker_set', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('sticker_title_name_gin_idx', 'sticker_set', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('sticker_tag_tag_name_idx', 'sticker_tag', ['tag_name'], unique=False, postgresql_using='gin', postgresql_ops={'tag_name': 'gin_trgm_ops'})
    op.create_index('tag_name_gin_idx', 'tag', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tag_name_gin_idx', table_name='tag')
    op.drop_index('sticker_tag_tag_name_idx', table_name='sticker_tag')
    op.drop_index('sticker_title_name_gin_idx', table_name='sticker_set')
    op.drop_index('sticker_set_name_gin_idx', table_name='sticker_set')
    op.drop_index('sticker_text_idx', table_name='sticker')
    # ### end Alembic commands ###
