"""Fix inline query request

Revision ID: 2daaec987d76
Revises: b179e344cc02
Create Date: 2018-11-30 15:20:04.702128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2daaec987d76"
down_revision = "b179e344cc02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inline_query_request",
        "duration",
        existing_type=postgresql.INTERVAL(),
        nullable=True,
    )
    op.alter_column(
        "inline_query_request", "next_offset", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inline_query_request",
        "next_offset",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "inline_query_request",
        "duration",
        existing_type=postgresql.INTERVAL(),
        nullable=False,
    )
    # ### end Alembic commands ###
