"""NSFW flag

Revision ID: 850a2cda19df
Revises: ef5c7ce8e2b7
Create Date: 2018-10-15 12:39:49.773763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850a2cda19df'
down_revision = 'ef5c7ce8e2b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sticker_set', sa.Column('nsfw', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sticker_set', 'nsfw')
    # ### end Alembic commands ###
