"""Sticker set review task

Revision ID: 6f86ae03db9b
Revises: 09ed6db5a163
Create Date: 2018-11-11 22:01:35.141385

"""
from alembic import op
import sqlalchemy as sa

import os
import sys
from sqlalchemy.orm.session import Session
# Set system path, so alembic is capable of finding the stickerfinder module
parent_dir = os.path.abspath(os.path.join(os.getcwd(), "..", "stickerfinder"))
sys.path.append(parent_dir)

from stickerfinder.models import StickerSet # noqa


# revision identifiers, used by Alembic.
revision = '6f86ae03db9b'
down_revision = '09ed6db5a163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'is_ban')
    op.add_column('sticker_set', sa.Column('reviewed', sa.Boolean(), nullable=False, server_default='False'))
    op.alter_column('sticker_set', 'reviewed', server_default=None)

    op.drop_column('sticker_set', 'newsfeed_sent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sticker_set', sa.Column('newsfeed_sent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('sticker_set', 'reviewed')
    op.add_column('chat', sa.Column('is_ban', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
