"""Remove inline query fields

Revision ID: 4cbb3aa3f114
Revises: 6007d57b5adb
Create Date: 2018-10-28 02:00:23.099554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4cbb3aa3f114'
down_revision = '6007d57b5adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inline_query', 'offset')
    op.drop_column('inline_query', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inline_query', sa.Column('duration', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    op.add_column('inline_query', sa.Column('offset', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
