"""Multi language support

Revision ID: 157ccc4d9d0b
Revises: 8b7c01c04a55
Create Date: 2018-11-03 05:34:38.616002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157ccc4d9d0b'
down_revision = '8b7c01c04a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'language',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chat', sa.Column('choosing_language', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tag', sa.Column('language', sa.String(), server_default='english', nullable=True))
    op.create_index(op.f('ix_tag_language'), 'tag', ['language'], unique=False)
    op.create_foreign_key(None, 'tag', 'language', ['language'], ['name'])
    op.add_column('task', sa.Column('message', sa.String(), nullable=True))
    op.add_column('user', sa.Column('language', sa.String(), server_default='english', nullable=True))
    op.create_index(op.f('ix_user_language'), 'user', ['language'], unique=False)
    op.create_foreign_key(None, 'user', 'language', ['language'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_language'), table_name='user')
    op.drop_column('user', 'language')
    op.drop_column('task', 'message')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_index(op.f('ix_tag_language'), table_name='tag')
    op.drop_column('tag', 'language')
    op.drop_column('chat', 'choosing_language')
    op.drop_table('language')
    # ### end Alembic commands ###
