"""random tagging and user authorized flag

Revision ID: 97be35ea927d
Revises: 7d6fd72f32db
Create Date: 2018-09-30 20:58:44.533065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97be35ea927d'
down_revision = '7d6fd72f32db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('tagging_random_sticker', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('user', sa.Column('authorized', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authorized')
    op.drop_column('chat', 'tagging_random_sticker')
    # ### end Alembic commands ###
