"""OnUpdate cascade

Revision ID: ad8be3fcd898
Revises: d270d8393fc6
Create Date: 2018-10-14 14:14:58.166532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8be3fcd898'
down_revision = 'd270d8393fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_current_sticker_set_name_fkey', 'chat', type_='foreignkey')
    op.create_foreign_key(None, 'chat', 'sticker_set', ['current_sticker_set_name'], ['name'], onupdate='cascade')
    op.drop_constraint('sticker_sticker_set_name_fkey', 'sticker', type_='foreignkey')
    op.create_foreign_key(None, 'sticker', 'sticker_set', ['sticker_set_name'], ['name'], onupdate='cascade')
    op.drop_constraint('task_sticker_set_name_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'sticker_set', ['sticker_set_name'], ['name'], onupdate='cascade')
    op.drop_constraint('vote_ban_sticker_set_name_fkey', 'vote_ban', type_='foreignkey')
    op.create_foreign_key(None, 'vote_ban', 'sticker_set', ['sticker_set_name'], ['name'], onupdate='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote_ban', type_='foreignkey')
    op.create_foreign_key('vote_ban_sticker_set_name_fkey', 'vote_ban', 'sticker_set', ['sticker_set_name'], ['name'])
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_sticker_set_name_fkey', 'task', 'sticker_set', ['sticker_set_name'], ['name'])
    op.drop_constraint(None, 'sticker', type_='foreignkey')
    op.create_foreign_key('sticker_sticker_set_name_fkey', 'sticker', 'sticker_set', ['sticker_set_name'], ['name'])
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.create_foreign_key('chat_current_sticker_set_name_fkey', 'chat', 'sticker_set', ['current_sticker_set_name'], ['name'])
    # ### end Alembic commands ###
