"""OnDelete cascade for sticker set

Revision ID: 963070a023d2
Revises: 850a2cda19df
Create Date: 2018-10-17 18:00:54.207481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963070a023d2'
down_revision = '850a2cda19df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('change_sticker_file_id_fkey', 'change', type_='foreignkey')
    op.create_foreign_key('change_sticker_file_id_fkey', 'change', 'sticker', ['sticker_file_id'], ['file_id'], ondelete='cascade')
    op.drop_constraint('chat_current_sticker_set_name_fkey', 'chat', type_='foreignkey')
    op.create_foreign_key('chat_current_sticker_set_name_fkey', 'chat', 'sticker_set', ['current_sticker_set_name'], ['name'], onupdate='cascade', ondelete='set null')
    op.drop_constraint('sticker_sticker_set_name_fkey', 'sticker', type_='foreignkey')
    op.create_foreign_key('sticker_sticker_set_name_fkey', 'sticker', 'sticker_set', ['sticker_set_name'], ['name'], onupdate='cascade', ondelete='cascade')
    op.drop_constraint('task_sticker_set_name_fkey', 'task', type_='foreignkey')
    op.create_foreign_key('task_sticker_set_name_fkey', 'task', 'sticker_set', ['sticker_set_name'], ['name'], onupdate='cascade', ondelete='cascade')
    op.drop_constraint('vote_ban_sticker_set_name_fkey', 'vote_ban', type_='foreignkey')
    op.create_foreign_key('vote_ban_sticker_set_name_fkey', 'vote_ban', 'sticker_set', ['sticker_set_name'], ['name'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vote_ban_sticker_set_name_fkey', 'vote_ban', type_='foreignkey')
    op.create_foreign_key('vote_ban_sticker_set_name_fkey', 'vote_ban', 'sticker_set', ['sticker_set_name'], ['name'], onupdate='CASCADE')
    op.drop_constraint('task_sticker_set_name_fkey', 'task', type_='foreignkey')
    op.create_foreign_key('task_sticker_set_name_fkey', 'task', 'sticker_set', ['sticker_set_name'], ['name'], onupdate='CASCADE')
    op.drop_constraint('sticker_sticker_set_name_fkey', 'sticker', type_='foreignkey')
    op.create_foreign_key('sticker_sticker_set_name_fkey', 'sticker', 'sticker_set', ['sticker_set_name'], ['name'], onupdate='CASCADE')
    op.drop_constraint('chat_current_sticker_set_name_fkey', 'chat', type_='foreignkey')
    op.create_foreign_key('chat_current_sticker_set_name_fkey', 'chat', 'sticker_set', ['current_sticker_set_name'], ['name'], onupdate='CASCADE')
    op.drop_constraint('change_sticker_file_id_fkey', 'change', type_='foreignkey')
    op.create_foreign_key('change_sticker_file_id_fkey', 'change', 'sticker', ['sticker_file_id'], ['file_id'])
    # ### end Alembic commands ###
