"""Remove text from changes

Revision ID: d270d8393fc6
Revises: 9e78c2866289
Create Date: 2018-10-13 02:09:25.430462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd270d8393fc6'
down_revision = '9e78c2866289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change', 'new_text')
    op.drop_column('change', 'old_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change', sa.Column('old_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('change', sa.Column('new_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
