"""Add original emojis

Revision ID: 9e78c2866289
Revises: da3156362cdc
Create Date: 2018-10-10 21:26:09.880363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e78c2866289'
down_revision = 'da3156362cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sticker', sa.Column('original_emojis', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sticker', 'original_emojis')
    # ### end Alembic commands ###
