"""Sticker pack search

Revision ID: 367c804c5170
Revises: 2daaec987d76
Create Date: 2018-12-01 11:20:26.790171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "367c804c5170"
down_revision = "2daaec987d76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inline_query",
        sa.Column("mode", sa.String(), nullable=False, server_default="sticker"),
    )
    op.alter_column("inline_query", "mode", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inline_query", "mode")
    # ### end Alembic commands ###
