"""Add several flags and columns.

Revision ID: 2f3f005f663d
Revises: Add several flags and columns
Create Date: 2018-09-26 22:43:43.227094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3f005f663d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'expecting_single_sticker')
    op.add_column('sticker_set', sa.Column('title', sa.String(), nullable=True))
    op.add_column('user', sa.Column('admin', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    op.create_unique_constraint('unique_user_username', 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_username', 'user', type_='unique')
    op.drop_column('user', 'username')
    op.drop_column('user', 'admin')
    op.drop_column('sticker_set', 'title')
    op.add_column('chat', sa.Column('expecting_single_sticker', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
