"""Rename default_language

Revision ID: 7ddf4da81c22
Revises: 6c854954ca33
Create Date: 2018-11-30 05:16:51.439164

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '7ddf4da81c22'
down_revision = '6c854954ca33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('change', 'default_language', new_column_name='is_default_language')
    op.alter_column('sticker_set', 'default_language', new_column_name='is_default_language')
    op.alter_column('tag', 'default_language', new_column_name='is_default_language')
    op.alter_column('task', 'default_language', new_column_name='is_default_language')
    op.alter_column('user', 'default_language', new_column_name='is_default_language')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('change', 'is_default_language', new_column_name='default_language')
    op.alter_column('sticker_set', 'is_default_language', new_column_name='default_language')
    op.alter_column('tag', 'is_default_language', new_column_name='default_language')
    op.alter_column('task', 'is_default_language', new_column_name='default_language')
    op.alter_column('user', 'is_default_language', new_column_name='default_language')
