"""Revert user changes

Revision ID: 1031ff4e8182
Revises: 199b4c5329ac
Create Date: 2018-10-05 14:21:40.552655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1031ff4e8182'
down_revision = '199b4c5329ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change', sa.Column('reverted', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('user', sa.Column('reverted', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reverted')
    op.drop_column('change', 'reverted')
    # ### end Alembic commands ###
