"""Stickerset deleted flag

Revision ID: 8b7c01c04a55
Revises: 4cbb3aa3f114
Create Date: 2018-10-31 23:35:48.866406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7c01c04a55'
down_revision = '4cbb3aa3f114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sticker_set', sa.Column('deleted', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sticker_set', 'deleted')
    # ### end Alembic commands ###
