"""Bannable stickers

Revision ID: 4ef4a89fe68b
Revises: 367c804c5170
Create Date: 2019-03-14 22:29:47.328495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef4a89fe68b'
down_revision = '367c804c5170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sticker', sa.Column('banned', sa.String(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sticker', 'banned')
    # ### end Alembic commands ###
