"""Add updated at to chat

Revision ID: 5333a07d4ea9
Revises: 4834f469968b
Create Date: 2019-04-04 18:56:20.028044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5333a07d4ea9"
down_revision = "4834f469968b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat", "updated_at")
    # ### end Alembic commands ###
