"""add chat to change

Revision ID: 9b7bc182196a
Revises: 9fa624eb51ab
Create Date: 2019-04-04 22:30:00.443446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7bc182196a'
down_revision = '9fa624eb51ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    op.add_column('change', sa.Column('message_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_change_chat_id'), 'change', ['chat_id'], unique=False)
    op.create_foreign_key('change_chat_id_fkey', 'change', 'chat', ['chat_id'], ['id'], onupdate='cascade', ondelete='cascade')
    op.drop_constraint('task_chat_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key('task_chat_id_fkey', 'task', 'chat', ['chat_id'], ['id'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_chat_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key('task_chat_id_fkey', 'task', 'chat', ['chat_id'], ['id'])
    op.drop_constraint('change_chat_id_fkey', 'change', type_='foreignkey')
    op.drop_index(op.f('ix_change_chat_id'), table_name='change')
    op.drop_column('change', 'message_id')
    op.drop_column('change', 'chat_id')
    # ### end Alembic commands ###
