"""Remove old tagging state flags

Revision ID: 4834f469968b
Revises: f972b83f1baa
Create Date: 2019-04-04 13:41:38.549490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4834f469968b'
down_revision = 'f972b83f1baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'tagging_random_sticker')
    op.drop_column('chat', 'fix_single_sticker')
    op.drop_column('chat', 'full_sticker_set')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('full_sticker_set', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('chat', sa.Column('fix_single_sticker', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('chat', sa.Column('tagging_random_sticker', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
