"""Is animated flag

Revision ID: 10aa7e1f95ec
Revises: 1cc051f593f8
Create Date: 2019-09-21 16:08:41.484695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "10aa7e1f95ec"
down_revision = "1cc051f593f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inline_query_request",
        "fuzzy",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=True,
    )
    op.add_column(
        "sticker",
        sa.Column("animated", sa.Boolean(), server_default="FALSE", nullable=False),
    )
    op.alter_column(
        "sticker",
        "banned",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sticker",
        "banned",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.drop_column("sticker", "animated")
    op.alter_column(
        "inline_query_request",
        "fuzzy",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
