"""Scan_scheduled flag

Revision ID: 3919491ac655
Revises: 7b11c2291b8f
Create Date: 2019-10-15 16:02:23.801381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3919491ac655"
down_revision = "7b11c2291b8f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sticker_set",
        sa.Column(
            "scan_scheduled", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sticker_set", "scan_scheduled")
    # ### end Alembic commands ###
