"""Sticker change cascade

Revision ID: be7577571b15
Revises: bde4d8e2916a
Create Date: 2019-08-09 03:08:37.434643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "be7577571b15"
down_revision = "bde4d8e2916a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
