"""Sticker change cascade

Revision ID: bde4d8e2916a
Revises: e948b90172ab
Create Date: 2019-08-09 02:50:27.818940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde4d8e2916a'
down_revision = 'e948b90172ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('change_sticker_file_id_fkey', 'change', type_='foreignkey')
    op.create_foreign_key(None, 'change', 'sticker', ['sticker_file_id'], ['file_id'], onupdate='cascade', ondelete='cascade')
    op.drop_constraint('chat_current_sticker_file_id_fkey', 'chat', type_='foreignkey')
    op.create_foreign_key(None, 'chat', 'sticker', ['current_sticker_file_id'], ['file_id'], onupdate='cascade', ondelete='SET NULL')
    op.drop_constraint('inline_query_sticker_file_id_fkey', 'inline_query', type_='foreignkey')
    op.create_foreign_key(None, 'inline_query', 'sticker', ['sticker_file_id'], ['file_id'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inline_query', type_='foreignkey')
    op.create_foreign_key('inline_query_sticker_file_id_fkey', 'inline_query', 'sticker', ['sticker_file_id'], ['file_id'])
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.create_foreign_key('chat_current_sticker_file_id_fkey', 'chat', 'sticker', ['current_sticker_file_id'], ['file_id'], ondelete='SET NULL')
    op.drop_constraint(None, 'change', type_='foreignkey')
    op.create_foreign_key('change_sticker_file_id_fkey', 'change', 'sticker', ['sticker_file_id'], ['file_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
