"""Add sticker.id again

Revision ID: 68251e30c693
Revises: 6f1c5993e9f0
Create Date: 2020-07-25 16:48:14.194597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68251e30c693"
down_revision = "6f1c5993e9f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create sequence sticker_id_seq")
    op.add_column(
        "sticker",
        sa.Column(
            "id",
            sa.BigInteger(),
            server_default=sa.text("nextval('sticker_id_seq'::regclass)"),
            nullable=False,
        ),
    )
    op.create_unique_constraint("sticker_unique_id", "sticker", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("drop sequence sticker_id_seq")
    op.drop_constraint("sticker_unique_id", "sticker", type_="unique")
    op.drop_column("sticker", "id")
    # ### end Alembic commands ###
